### ISSUE TITLE
Check only Ipads and tablets

### ISSUE THREAD

**Issue by vksdgreat** [marcovtwout/yii-detectmobilebrowser#1]
Hi, Using detectmobilebrowser i want to check only tablets and ipads. I have two different functionalities in my website in one i want it to work for all mobile devices including tablets and ipads and in other section i want it to work only for tablets and ipads so hoe to detect only tablets and ipads using detectmobilebrowser extension

**Comment by marcovtwout** [comment]
You can't: you'd have to use a more specific solution, maybe this? http://mobiledetect.net/
